name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate test data
        run: npm run validate

      - name: Build React project with static API
        run: npm run build:static
        env:
          CI: false

      - name: Create deployment info
        run: |
          echo "# MCQ Test Platform - Static Deployment" > build/DEPLOYMENT_INFO.md
          echo "" >> build/DEPLOYMENT_INFO.md
          echo "This is a static deployment of the MCQ Test Platform." >> build/DEPLOYMENT_INFO.md
          echo "Generated on: $(date)" >> build/DEPLOYMENT_INFO.md
          echo "" >> build/DEPLOYMENT_INFO.md
          echo "## Available API Endpoints (Static):" >> build/DEPLOYMENT_INFO.md
          echo "- \`/api/db.json\` - Main database" >> build/DEPLOYMENT_INFO.md
          echo "- \`/api/tests.json\` - All active tests" >> build/DEPLOYMENT_INFO.md
          echo "- \`/api/tests-{id}.json\` - Individual test by ID" >> build/DEPLOYMENT_INFO.md
          echo "- \`/api/test-files.json\` - List of available test files" >> build/DEPLOYMENT_INFO.md
          echo "- \`/api/testfiles/{folder}/{filename}\` - Direct test file access" >> build/DEPLOYMENT_INFO.md
          echo "- \`/api/deployment-info.json\` - Deployment metadata" >> build/DEPLOYMENT_INFO.md

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
